### PR TITLE
support npm

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@MrMoranXP has created a fork for npm support.

this project should include a "umd" loader header and take over the npm package

**Comment by rdallasgray** [comment]
Hi -- thanks for the PR. Unfortunately I can't merge this for several reasons:

- The branch has conflicts (you'd need to resolve these manually)
- This wouldn't be compatible with environments which don't use CommonJS -- it would need to include a header like, e.g, the one used by Backbone: https://github.com/jashkenas/backbone/blob/master/backbone.js#L8 (I'm not sure if this is what you mean by a UMD loader header)
- The package.json itself isn't really up to scratch (clearly I'm not going to merge it when it lists a different repo as the source and doesn't list me as an author!)

I'm guessing you intended to raise this as an issue rather than a PR, so I'm going to close. I recognise the need to make Bez available as a CommonJS package, though, so I will try to make time to do so.

**Comment by graingert** [comment]
Yes that's what I mean by UMD

**Comment by rdallasgray** [comment]
OK, please see #9.

You can test install this like so:

```
npm install --save rdallasgray/bez#npm
```

I'd be grateful if you would test and let me know if everything is working correctly.

**Pull request closed without merging**
